/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mostml.ui.internal.MostmlActivator;

public class MoStMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MostmlActivator.getInstance().getInjector("org.xtext.example.mostml.MoStML");
	}

}
