/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mostml.moStML.ATTRIBUTEVALUE;
import org.xtext.example.mostml.moStML.MoStMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ATTRIBUTEVALUE</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ATTRIBUTEVALUEImpl extends MinimalEObjectImpl.Container implements ATTRIBUTEVALUE
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ATTRIBUTEVALUEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoStMLPackage.Literals.ATTRIBUTEVALUE;
  }

} //ATTRIBUTEVALUEImpl
