/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mostml.moStML.COMPARISONOPERATOR;
import org.xtext.example.mostml.moStML.MoStMLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>COMPARISONOPERATOR</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class COMPARISONOPERATORImpl extends MinimalEObjectImpl.Container implements COMPARISONOPERATOR
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected COMPARISONOPERATORImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoStMLPackage.Literals.COMPARISONOPERATOR;
  }

} //COMPARISONOPERATORImpl
