/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mostml.moStML.MoStMLPackage;
import org.xtext.example.mostml.moStML.NOTEQUAL;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>NOTEQUAL</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.impl.NOTEQUALImpl#getNotEqual <em>Not Equal</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NOTEQUALImpl extends COMPARISONOPERATORImpl implements NOTEQUAL
{
  /**
   * The default value of the '{@link #getNotEqual() <em>Not Equal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotEqual()
   * @generated
   * @ordered
   */
  protected static final String NOT_EQUAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNotEqual() <em>Not Equal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotEqual()
   * @generated
   * @ordered
   */
  protected String notEqual = NOT_EQUAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NOTEQUALImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoStMLPackage.Literals.NOTEQUAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNotEqual()
  {
    return notEqual;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNotEqual(String newNotEqual)
  {
    String oldNotEqual = notEqual;
    notEqual = newNotEqual;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MoStMLPackage.NOTEQUAL__NOT_EQUAL, oldNotEqual, notEqual));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MoStMLPackage.NOTEQUAL__NOT_EQUAL:
        return getNotEqual();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MoStMLPackage.NOTEQUAL__NOT_EQUAL:
        setNotEqual((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MoStMLPackage.NOTEQUAL__NOT_EQUAL:
        setNotEqual(NOT_EQUAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MoStMLPackage.NOTEQUAL__NOT_EQUAL:
        return NOT_EQUAL_EDEFAULT == null ? notEqual != null : !NOT_EQUAL_EDEFAULT.equals(notEqual);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (notEqual: ");
    result.append(notEqual);
    result.append(')');
    return result.toString();
  }

} //NOTEQUALImpl
