/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mostml.moStML.MoStMLPackage;
import org.xtext.example.mostml.moStML.SPINNINGSPEED;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SPINNINGSPEED</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.impl.SPINNINGSPEEDImpl#getSpinningspeed <em>Spinningspeed</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SPINNINGSPEEDImpl extends UNITImpl implements SPINNINGSPEED
{
  /**
   * The default value of the '{@link #getSpinningspeed() <em>Spinningspeed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpinningspeed()
   * @generated
   * @ordered
   */
  protected static final String SPINNINGSPEED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSpinningspeed() <em>Spinningspeed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpinningspeed()
   * @generated
   * @ordered
   */
  protected String spinningspeed = SPINNINGSPEED_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SPINNINGSPEEDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoStMLPackage.Literals.SPINNINGSPEED;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSpinningspeed()
  {
    return spinningspeed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpinningspeed(String newSpinningspeed)
  {
    String oldSpinningspeed = spinningspeed;
    spinningspeed = newSpinningspeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MoStMLPackage.SPINNINGSPEED__SPINNINGSPEED, oldSpinningspeed, spinningspeed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MoStMLPackage.SPINNINGSPEED__SPINNINGSPEED:
        return getSpinningspeed();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MoStMLPackage.SPINNINGSPEED__SPINNINGSPEED:
        setSpinningspeed((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MoStMLPackage.SPINNINGSPEED__SPINNINGSPEED:
        setSpinningspeed(SPINNINGSPEED_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MoStMLPackage.SPINNINGSPEED__SPINNINGSPEED:
        return SPINNINGSPEED_EDEFAULT == null ? spinningspeed != null : !SPINNINGSPEED_EDEFAULT.equals(spinningspeed);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (spinningspeed: ");
    result.append(spinningspeed);
    result.append(')');
    return result.toString();
  }

} //SPINNINGSPEEDImpl
