/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mostml.moStML.MoStMLPackage;
import org.xtext.example.mostml.moStML.UNIT;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UNIT</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UNITImpl extends MinimalEObjectImpl.Container implements UNIT
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UNITImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MoStMLPackage.Literals.UNIT;
  }

} //UNITImpl
