/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MoStMLStandaloneSetup extends MoStMLStandaloneSetupGenerated {

	public static void doSetup() {
		new MoStMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
