/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AF</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.AF#getAf <em>Af</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getAF()
 * @model
 * @generated
 */
public interface AF extends CTLOperator
{
  /**
   * Returns the value of the '<em><b>Af</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Af</em>' attribute.
   * @see #setAf(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getAF_Af()
   * @model
   * @generated
   */
  String getAf();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.AF#getAf <em>Af</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Af</em>' attribute.
   * @see #getAf()
   * @generated
   */
  void setAf(String value);

} // AF
