/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ATTRIBUTECONTION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.ATTRIBUTECONTION#getAttributeName <em>Attribute Name</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.ATTRIBUTECONTION#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.ATTRIBUTECONTION#getAttributeValue <em>Attribute Value</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.ATTRIBUTECONTION#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getATTRIBUTECONTION()
 * @model
 * @generated
 */
public interface ATTRIBUTECONTION extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Name</em>' attribute.
   * @see #setAttributeName(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getATTRIBUTECONTION_AttributeName()
   * @model
   * @generated
   */
  String getAttributeName();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.ATTRIBUTECONTION#getAttributeName <em>Attribute Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Name</em>' attribute.
   * @see #getAttributeName()
   * @generated
   */
  void setAttributeName(String value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference.
   * @see #setOperator(COMPARISONOPERATOR)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getATTRIBUTECONTION_Operator()
   * @model containment="true"
   * @generated
   */
  COMPARISONOPERATOR getOperator();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.ATTRIBUTECONTION#getOperator <em>Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' containment reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(COMPARISONOPERATOR value);

  /**
   * Returns the value of the '<em><b>Attribute Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Value</em>' containment reference.
   * @see #setAttributeValue(ATTRIBUTEVALUE)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getATTRIBUTECONTION_AttributeValue()
   * @model containment="true"
   * @generated
   */
  ATTRIBUTEVALUE getAttributeValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.ATTRIBUTECONTION#getAttributeValue <em>Attribute Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Value</em>' containment reference.
   * @see #getAttributeValue()
   * @generated
   */
  void setAttributeValue(ATTRIBUTEVALUE value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mostml.moStML.UNIT}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getATTRIBUTECONTION_Unit()
   * @model containment="true"
   * @generated
   */
  EList<UNIT> getUnit();

} // ATTRIBUTECONTION
