/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COMPARISONOPERATOR</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getCOMPARISONOPERATOR()
 * @model
 * @generated
 */
public interface COMPARISONOPERATOR extends EObject
{
} // COMPARISONOPERATOR
