/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CONSTRAINT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.CONSTRAINT#getConstraintReqID <em>Constraint Req ID</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.CONSTRAINT#getPreConstraintConditions <em>Pre Constraint Conditions</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.CONSTRAINT#getRelations <em>Relations</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.CONSTRAINT#getPostConstraintCondition <em>Post Constraint Condition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getCONSTRAINT()
 * @model
 * @generated
 */
public interface CONSTRAINT extends Requirement
{
  /**
   * Returns the value of the '<em><b>Constraint Req ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint Req ID</em>' containment reference.
   * @see #setConstraintReqID(ReqID)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getCONSTRAINT_ConstraintReqID()
   * @model containment="true"
   * @generated
   */
  ReqID getConstraintReqID();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.CONSTRAINT#getConstraintReqID <em>Constraint Req ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint Req ID</em>' containment reference.
   * @see #getConstraintReqID()
   * @generated
   */
  void setConstraintReqID(ReqID value);

  /**
   * Returns the value of the '<em><b>Pre Constraint Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Constraint Conditions</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getCONSTRAINT_PreConstraintConditions()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getPreConstraintConditions();

  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mostml.moStML.RELATION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getCONSTRAINT_Relations()
   * @model containment="true"
   * @generated
   */
  EList<RELATION> getRelations();

  /**
   * Returns the value of the '<em><b>Post Constraint Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post Constraint Condition</em>' containment reference.
   * @see #setPostConstraintCondition(EObject)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getCONSTRAINT_PostConstraintCondition()
   * @model containment="true"
   * @generated
   */
  EObject getPostConstraintCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.CONSTRAINT#getPostConstraintCondition <em>Post Constraint Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post Constraint Condition</em>' containment reference.
   * @see #getPostConstraintCondition()
   * @generated
   */
  void setPostConstraintCondition(EObject value);

} // CONSTRAINT
