/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DIVISION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.DIVISION#getDivision <em>Division</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getDIVISION()
 * @model
 * @generated
 */
public interface DIVISION extends ARITHMETICOPERATOR
{
  /**
   * Returns the value of the '<em><b>Division</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Division</em>' attribute.
   * @see #setDivision(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getDIVISION_Division()
   * @model
   * @generated
   */
  String getDivision();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.DIVISION#getDivision <em>Division</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Division</em>' attribute.
   * @see #getDivision()
   * @generated
   */
  void setDivision(String value);

} // DIVISION
