/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EF</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.EF#getEf <em>Ef</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getEF()
 * @model
 * @generated
 */
public interface EF extends CTLOperator
{
  /**
   * Returns the value of the '<em><b>Ef</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ef</em>' attribute.
   * @see #setEf(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getEF_Ef()
   * @model
   * @generated
   */
  String getEf();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.EF#getEf <em>Ef</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ef</em>' attribute.
   * @see #getEf()
   * @generated
   */
  void setEf(String value);

} // EF
