/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.EG#getEg <em>Eg</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getEG()
 * @model
 * @generated
 */
public interface EG extends CTLOperator
{
  /**
   * Returns the value of the '<em><b>Eg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eg</em>' attribute.
   * @see #setEg(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getEG_Eg()
   * @model
   * @generated
   */
  String getEg();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.EG#getEg <em>Eg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eg</em>' attribute.
   * @see #getEg()
   * @generated
   */
  void setEg(String value);

} // EG
