/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>G</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.G#getG <em>G</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getG()
 * @model
 * @generated
 */
public interface G extends LTLOperator
{
  /**
   * Returns the value of the '<em><b>G</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>G</em>' attribute.
   * @see #setG(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getG_G()
   * @model
   * @generated
   */
  String getG();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.G#getG <em>G</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>G</em>' attribute.
   * @see #getG()
   * @generated
   */
  void setG(String value);

} // G
