/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GREATER</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.GREATER#getGreater <em>Greater</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getGREATER()
 * @model
 * @generated
 */
public interface GREATER extends COMPARISONOPERATOR
{
  /**
   * Returns the value of the '<em><b>Greater</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greater</em>' attribute.
   * @see #setGreater(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getGREATER_Greater()
   * @model
   * @generated
   */
  String getGreater();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.GREATER#getGreater <em>Greater</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greater</em>' attribute.
   * @see #getGreater()
   * @generated
   */
  void setGreater(String value);

} // GREATER
