/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GREATEQUAL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.GREATEQUAL#getGreateEqual <em>Greate Equal</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getGREATEQUAL()
 * @model
 * @generated
 */
public interface GREATEQUAL extends COMPARISONOPERATOR
{
  /**
   * Returns the value of the '<em><b>Greate Equal</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greate Equal</em>' attribute list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getGREATEQUAL_GreateEqual()
   * @model unique="false"
   * @generated
   */
  EList<String> getGreateEqual();

} // GREATEQUAL
