/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LESS</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.LESS#getLess <em>Less</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getLESS()
 * @model
 * @generated
 */
public interface LESS extends COMPARISONOPERATOR
{
  /**
   * Returns the value of the '<em><b>Less</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Less</em>' attribute list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getLESS_Less()
   * @model unique="false"
   * @generated
   */
  EList<String> getLess();

} // LESS
