/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MODE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.MODE#getModeReqID <em>Mode Req ID</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.MODE#getPreModeConditions <em>Pre Mode Conditions</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.MODE#getPreRelations <em>Pre Relations</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.MODE#getPostModeCondition <em>Post Mode Condition</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getMODE()
 * @model
 * @generated
 */
public interface MODE extends Requirement
{
  /**
   * Returns the value of the '<em><b>Mode Req ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mode Req ID</em>' containment reference.
   * @see #setModeReqID(ReqID)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getMODE_ModeReqID()
   * @model containment="true"
   * @generated
   */
  ReqID getModeReqID();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.MODE#getModeReqID <em>Mode Req ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mode Req ID</em>' containment reference.
   * @see #getModeReqID()
   * @generated
   */
  void setModeReqID(ReqID value);

  /**
   * Returns the value of the '<em><b>Pre Mode Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Mode Conditions</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getMODE_PreModeConditions()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getPreModeConditions();

  /**
   * Returns the value of the '<em><b>Pre Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mostml.moStML.RELATION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Relations</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getMODE_PreRelations()
   * @model containment="true"
   * @generated
   */
  EList<RELATION> getPreRelations();

  /**
   * Returns the value of the '<em><b>Post Mode Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post Mode Condition</em>' containment reference.
   * @see #setPostModeCondition(MODECONDITION)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getMODE_PostModeCondition()
   * @model containment="true"
   * @generated
   */
  MODECONDITION getPostModeCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.MODE#getPostModeCondition <em>Post Mode Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post Mode Condition</em>' containment reference.
   * @see #getPostModeCondition()
   * @generated
   */
  void setPostModeCondition(MODECONDITION value);

} // MODE
