/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mo St</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.MoSt#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getMoSt()
 * @model
 * @generated
 */
public interface MoSt extends EObject
{
  /**
   * Returns the value of the '<em><b>Model</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getMoSt_Model()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getModel();

} // MoSt
