/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mostml.moStML.MoStMLPackage
 * @generated
 */
public interface MoStMLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MoStMLFactory eINSTANCE = org.xtext.example.mostml.moStML.impl.MoStMLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Mo St</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mo St</em>'.
   * @generated
   */
  MoSt createMoSt();

  /**
   * Returns a new object of class '<em>NL Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NL Requirement</em>'.
   * @generated
   */
  NLRequirement createNLRequirement();

  /**
   * Returns a new object of class '<em>Requirement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Requirement</em>'.
   * @generated
   */
  Requirement createRequirement();

  /**
   * Returns a new object of class '<em>Environment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Environment</em>'.
   * @generated
   */
  Environment createEnvironment();

  /**
   * Returns a new object of class '<em>MODE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MODE</em>'.
   * @generated
   */
  MODE createMODE();

  /**
   * Returns a new object of class '<em>STATE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STATE</em>'.
   * @generated
   */
  STATE createSTATE();

  /**
   * Returns a new object of class '<em>CONSTRAINT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CONSTRAINT</em>'.
   * @generated
   */
  CONSTRAINT createCONSTRAINT();

  /**
   * Returns a new object of class '<em>PROPERTY</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>PROPERTY</em>'.
   * @generated
   */
  PROPERTY createPROPERTY();

  /**
   * Returns a new object of class '<em>RANG</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RANG</em>'.
   * @generated
   */
  RANG createRANG();

  /**
   * Returns a new object of class '<em>CTL Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CTL Operator</em>'.
   * @generated
   */
  CTLOperator createCTLOperator();

  /**
   * Returns a new object of class '<em>AX</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AX</em>'.
   * @generated
   */
  AX createAX();

  /**
   * Returns a new object of class '<em>EG</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EG</em>'.
   * @generated
   */
  EG createEG();

  /**
   * Returns a new object of class '<em>EF</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EF</em>'.
   * @generated
   */
  EF createEF();

  /**
   * Returns a new object of class '<em>AF</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AF</em>'.
   * @generated
   */
  AF createAF();

  /**
   * Returns a new object of class '<em>AG</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AG</em>'.
   * @generated
   */
  AG createAG();

  /**
   * Returns a new object of class '<em>LTL Operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LTL Operator</em>'.
   * @generated
   */
  LTLOperator createLTLOperator();

  /**
   * Returns a new object of class '<em>F</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>F</em>'.
   * @generated
   */
  F createF();

  /**
   * Returns a new object of class '<em>G</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>G</em>'.
   * @generated
   */
  G createG();

  /**
   * Returns a new object of class '<em>X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>X</em>'.
   * @generated
   */
  X createX();

  /**
   * Returns a new object of class '<em>RELATION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RELATION</em>'.
   * @generated
   */
  RELATION createRELATION();

  /**
   * Returns a new object of class '<em>SIGNALCONDITION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SIGNALCONDITION</em>'.
   * @generated
   */
  SIGNALCONDITION createSIGNALCONDITION();

  /**
   * Returns a new object of class '<em>Req ID</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Req ID</em>'.
   * @generated
   */
  ReqID createReqID();

  /**
   * Returns a new object of class '<em>ATTRIBUTECONTION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ATTRIBUTECONTION</em>'.
   * @generated
   */
  ATTRIBUTECONTION createATTRIBUTECONTION();

  /**
   * Returns a new object of class '<em>UNIT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>UNIT</em>'.
   * @generated
   */
  UNIT createUNIT();

  /**
   * Returns a new object of class '<em>WEIGHT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>WEIGHT</em>'.
   * @generated
   */
  WEIGHT createWEIGHT();

  /**
   * Returns a new object of class '<em>TIME</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>TIME</em>'.
   * @generated
   */
  TIME createTIME();

  /**
   * Returns a new object of class '<em>SPEED</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SPEED</em>'.
   * @generated
   */
  SPEED createSPEED();

  /**
   * Returns a new object of class '<em>ATTRIBUTEVALUE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ATTRIBUTEVALUE</em>'.
   * @generated
   */
  ATTRIBUTEVALUE createATTRIBUTEVALUE();

  /**
   * Returns a new object of class '<em>STRINGTYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STRINGTYPE</em>'.
   * @generated
   */
  STRINGTYPE createSTRINGTYPE();

  /**
   * Returns a new object of class '<em>INTTYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>INTTYPE</em>'.
   * @generated
   */
  INTTYPE createINTTYPE();

  /**
   * Returns a new object of class '<em>BOOLEANTYPE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BOOLEANTYPE</em>'.
   * @generated
   */
  BOOLEANTYPE createBOOLEANTYPE();

  /**
   * Returns a new object of class '<em>STATECONDITON</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>STATECONDITON</em>'.
   * @generated
   */
  STATECONDITON createSTATECONDITON();

  /**
   * Returns a new object of class '<em>MODECONDITION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MODECONDITION</em>'.
   * @generated
   */
  MODECONDITION createMODECONDITION();

  /**
   * Returns a new object of class '<em>ARITHMETICCONDITION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ARITHMETICCONDITION</em>'.
   * @generated
   */
  ARITHMETICCONDITION createARITHMETICCONDITION();

  /**
   * Returns a new object of class '<em>ARITHMETICOPERATOR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ARITHMETICOPERATOR</em>'.
   * @generated
   */
  ARITHMETICOPERATOR createARITHMETICOPERATOR();

  /**
   * Returns a new object of class '<em>MODULE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MODULE</em>'.
   * @generated
   */
  MODULE createMODULE();

  /**
   * Returns a new object of class '<em>DIVISION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DIVISION</em>'.
   * @generated
   */
  DIVISION createDIVISION();

  /**
   * Returns a new object of class '<em>MULTIPLICATION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>MULTIPLICATION</em>'.
   * @generated
   */
  MULTIPLICATION createMULTIPLICATION();

  /**
   * Returns a new object of class '<em>SUBTRACTION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SUBTRACTION</em>'.
   * @generated
   */
  SUBTRACTION createSUBTRACTION();

  /**
   * Returns a new object of class '<em>ADD</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ADD</em>'.
   * @generated
   */
  ADD createADD();

  /**
   * Returns a new object of class '<em>COMPARISONOPERATOR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COMPARISONOPERATOR</em>'.
   * @generated
   */
  COMPARISONOPERATOR createCOMPARISONOPERATOR();

  /**
   * Returns a new object of class '<em>NOT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NOT</em>'.
   * @generated
   */
  NOT createNOT();

  /**
   * Returns a new object of class '<em>GREATEQUAL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GREATEQUAL</em>'.
   * @generated
   */
  GREATEQUAL createGREATEQUAL();

  /**
   * Returns a new object of class '<em>LESSEQUAL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LESSEQUAL</em>'.
   * @generated
   */
  LESSEQUAL createLESSEQUAL();

  /**
   * Returns a new object of class '<em>NOTEQUAL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>NOTEQUAL</em>'.
   * @generated
   */
  NOTEQUAL createNOTEQUAL();

  /**
   * Returns a new object of class '<em>GREATER</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>GREATER</em>'.
   * @generated
   */
  GREATER createGREATER();

  /**
   * Returns a new object of class '<em>LESS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>LESS</em>'.
   * @generated
   */
  LESS createLESS();

  /**
   * Returns a new object of class '<em>EQUAL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EQUAL</em>'.
   * @generated
   */
  EQUAL createEQUAL();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MoStMLPackage getMoStMLPackage();

} //MoStMLFactory
