/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>PROPERTY</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.PROPERTY#getPropertyReqID <em>Property Req ID</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.PROPERTY#getPreOperator <em>Pre Operator</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.PROPERTY#getPrePropertyConditions <em>Pre Property Conditions</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.PROPERTY#getPreRelations <em>Pre Relations</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.PROPERTY#getPostOperator <em>Post Operator</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.PROPERTY#getPostPropertyConditions <em>Post Property Conditions</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.PROPERTY#getPostRelations <em>Post Relations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY()
 * @model
 * @generated
 */
public interface PROPERTY extends Requirement
{
  /**
   * Returns the value of the '<em><b>Property Req ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Req ID</em>' containment reference.
   * @see #setPropertyReqID(ReqID)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY_PropertyReqID()
   * @model containment="true"
   * @generated
   */
  ReqID getPropertyReqID();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.PROPERTY#getPropertyReqID <em>Property Req ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property Req ID</em>' containment reference.
   * @see #getPropertyReqID()
   * @generated
   */
  void setPropertyReqID(ReqID value);

  /**
   * Returns the value of the '<em><b>Pre Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Operator</em>' containment reference.
   * @see #setPreOperator(EObject)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY_PreOperator()
   * @model containment="true"
   * @generated
   */
  EObject getPreOperator();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.PROPERTY#getPreOperator <em>Pre Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre Operator</em>' containment reference.
   * @see #getPreOperator()
   * @generated
   */
  void setPreOperator(EObject value);

  /**
   * Returns the value of the '<em><b>Pre Property Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Property Conditions</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY_PrePropertyConditions()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getPrePropertyConditions();

  /**
   * Returns the value of the '<em><b>Pre Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mostml.moStML.RELATION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Relations</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY_PreRelations()
   * @model containment="true"
   * @generated
   */
  EList<RELATION> getPreRelations();

  /**
   * Returns the value of the '<em><b>Post Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post Operator</em>' containment reference.
   * @see #setPostOperator(EObject)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY_PostOperator()
   * @model containment="true"
   * @generated
   */
  EObject getPostOperator();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.PROPERTY#getPostOperator <em>Post Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post Operator</em>' containment reference.
   * @see #getPostOperator()
   * @generated
   */
  void setPostOperator(EObject value);

  /**
   * Returns the value of the '<em><b>Post Property Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post Property Conditions</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY_PostPropertyConditions()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getPostPropertyConditions();

  /**
   * Returns the value of the '<em><b>Post Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mostml.moStML.RELATION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post Relations</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getPROPERTY_PostRelations()
   * @model containment="true"
   * @generated
   */
  EList<RELATION> getPostRelations();

} // PROPERTY
