/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RELATION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.RELATION#getRelaion <em>Relaion</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getRELATION()
 * @model
 * @generated
 */
public interface RELATION extends EObject
{
  /**
   * Returns the value of the '<em><b>Relaion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relaion</em>' attribute.
   * @see #setRelaion(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getRELATION_Relaion()
   * @model
   * @generated
   */
  String getRelaion();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.RELATION#getRelaion <em>Relaion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relaion</em>' attribute.
   * @see #getRelaion()
   * @generated
   */
  void setRelaion(String value);

} // RELATION
