/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Req ID</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.ReqID#getReqID <em>Req ID</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getReqID()
 * @model
 * @generated
 */
public interface ReqID extends EObject
{
  /**
   * Returns the value of the '<em><b>Req ID</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req ID</em>' attribute list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getReqID_ReqID()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getReqID();

} // ReqID
