/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SPINNINGSPEED</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.SPINNINGSPEED#getSpinningspeed <em>Spinningspeed</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSPINNINGSPEED()
 * @model
 * @generated
 */
public interface SPINNINGSPEED extends UNIT
{
  /**
   * Returns the value of the '<em><b>Spinningspeed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spinningspeed</em>' attribute.
   * @see #setSpinningspeed(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSPINNINGSPEED_Spinningspeed()
   * @model
   * @generated
   */
  String getSpinningspeed();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.SPINNINGSPEED#getSpinningspeed <em>Spinningspeed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spinningspeed</em>' attribute.
   * @see #getSpinningspeed()
   * @generated
   */
  void setSpinningspeed(String value);

} // SPINNINGSPEED
