/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>STATE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.STATE#getStateReqID <em>State Req ID</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.STATE#getPreStateConditions <em>Pre State Conditions</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.STATE#getRelations <em>Relations</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.STATE#getPostStateConditions <em>Post State Conditions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATE()
 * @model
 * @generated
 */
public interface STATE extends Requirement
{
  /**
   * Returns the value of the '<em><b>State Req ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Req ID</em>' containment reference.
   * @see #setStateReqID(ReqID)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATE_StateReqID()
   * @model containment="true"
   * @generated
   */
  ReqID getStateReqID();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.STATE#getStateReqID <em>State Req ID</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State Req ID</em>' containment reference.
   * @see #getStateReqID()
   * @generated
   */
  void setStateReqID(ReqID value);

  /**
   * Returns the value of the '<em><b>Pre State Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre State Conditions</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATE_PreStateConditions()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getPreStateConditions();

  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mostml.moStML.RELATION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATE_Relations()
   * @model containment="true"
   * @generated
   */
  EList<RELATION> getRelations();

  /**
   * Returns the value of the '<em><b>Post State Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mostml.moStML.STATECONDITON}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post State Conditions</em>' containment reference list.
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATE_PostStateConditions()
   * @model containment="true"
   * @generated
   */
  EList<STATECONDITON> getPostStateConditions();

} // STATE
