/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>STATECONDITON</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.STATECONDITON#getStateName <em>State Name</em>}</li>
 *   <li>{@link org.xtext.example.mostml.moStML.STATECONDITON#getCompOperator <em>Comp Operator</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATECONDITON()
 * @model
 * @generated
 */
public interface STATECONDITON extends EObject
{
  /**
   * Returns the value of the '<em><b>State Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Name</em>' attribute.
   * @see #setStateName(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATECONDITON_StateName()
   * @model
   * @generated
   */
  String getStateName();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.STATECONDITON#getStateName <em>State Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State Name</em>' attribute.
   * @see #getStateName()
   * @generated
   */
  void setStateName(String value);

  /**
   * Returns the value of the '<em><b>Comp Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp Operator</em>' containment reference.
   * @see #setCompOperator(COMPARISONOPERATOR)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSTATECONDITON_CompOperator()
   * @model containment="true"
   * @generated
   */
  COMPARISONOPERATOR getCompOperator();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.STATECONDITON#getCompOperator <em>Comp Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp Operator</em>' containment reference.
   * @see #getCompOperator()
   * @generated
   */
  void setCompOperator(COMPARISONOPERATOR value);

} // STATECONDITON
