/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SUBTRACTION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.SUBTRACTION#getSubstraction <em>Substraction</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSUBTRACTION()
 * @model
 * @generated
 */
public interface SUBTRACTION extends ARITHMETICOPERATOR
{
  /**
   * Returns the value of the '<em><b>Substraction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substraction</em>' attribute.
   * @see #setSubstraction(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getSUBTRACTION_Substraction()
   * @model
   * @generated
   */
  String getSubstraction();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.SUBTRACTION#getSubstraction <em>Substraction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Substraction</em>' attribute.
   * @see #getSubstraction()
   * @generated
   */
  void setSubstraction(String value);

} // SUBTRACTION
