/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TEMPERATURE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.TEMPERATURE#getTemperature <em>Temperature</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getTEMPERATURE()
 * @model
 * @generated
 */
public interface TEMPERATURE extends UNIT
{
  /**
   * Returns the value of the '<em><b>Temperature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temperature</em>' attribute.
   * @see #setTemperature(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getTEMPERATURE_Temperature()
   * @model
   * @generated
   */
  String getTemperature();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.TEMPERATURE#getTemperature <em>Temperature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temperature</em>' attribute.
   * @see #getTemperature()
   * @generated
   */
  void setTemperature(String value);

} // TEMPERATURE
