/**
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WEIGHT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.WEIGHT#getWeight <em>Weight</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getWEIGHT()
 * @model
 * @generated
 */
public interface WEIGHT extends UNIT
{
  /**
   * Returns the value of the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' attribute.
   * @see #setWeight(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getWEIGHT_Weight()
   * @model
   * @generated
   */
  String getWeight();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.WEIGHT#getWeight <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' attribute.
   * @see #getWeight()
   * @generated
   */
  void setWeight(String value);

} // WEIGHT
