/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.moStML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>X</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mostml.moStML.X#getX <em>X</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mostml.moStML.MoStMLPackage#getX()
 * @model
 * @generated
 */
public interface X extends LTLOperator
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(String)
   * @see org.xtext.example.mostml.moStML.MoStMLPackage#getX_X()
   * @model
   * @generated
   */
  String getX();

  /**
   * Sets the value of the '{@link org.xtext.example.mostml.moStML.X#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(String value);

} // X
