/*
 * generated by Xtext 2.27.0
 */
package org.xtext.example.mostml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mostml.ui.internal.MostmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MoStMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MostmlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MostmlActivator activator = MostmlActivator.getInstance();
		return activator != null ? activator.getInjector(MostmlActivator.ORG_XTEXT_EXAMPLE_MOSTML_MOSTML) : null;
	}

}
