/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mostml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MoStMLUiModule extends AbstractMoStMLUiModule {

	public MoStMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
